#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from safetensors.torch import save_file as safe_save_file
except Exception:  # pragma: no cover
    safe_save_file = None

from src.diffusers.models.transformers.transformer_pixeldit import PIXELDIT_PRESET_CONFIGS, PixelDiTTransformer2DModel


def get_args():
    parser = argparse.ArgumentParser(description="Convert diffusers PixelDiT model back to legacy checkpoint format.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to diffusers model directory.")
    parser.add_argument("--output_path", type=str, required=True, help="Output checkpoint path (.safetensors or .bin).")
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional conversion_metadata.json generated by convert_pixeldit_to_diffusers.py.",
    )
    parser.add_argument("--prefix", type=str, default="", help="Optional prefix for exported state-dict keys.")
    parser.add_argument("--safe-serialization", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def _infer_model_type_from_config(model_config) -> str | None:
    model_type = getattr(model_config, "model_type", None)
    if model_type in PIXELDIT_PRESET_CONFIGS:
        return model_type

    sample_size = int(getattr(model_config, "sample_size", 256))
    patch_size = int(getattr(model_config, "patch_size", 16))
    hidden_size = int(getattr(model_config, "hidden_size", 1152))
    patch_depth = int(getattr(model_config, "patch_depth", 26))
    pixel_depth = int(getattr(model_config, "pixel_depth", 4))

    for preset_name, preset in PIXELDIT_PRESET_CONFIGS.items():
        if (
            sample_size == int(preset["sample_size"])
            and patch_size == int(preset["patch_size"])
            and hidden_size == int(preset["hidden_size"])
            and patch_depth == int(preset["patch_depth"])
            and pixel_depth == int(preset["pixel_depth"])
        ):
            return preset_name
    return None


def main():
    args = get_args()

    model_path = Path(args.model_path)
    transformer_path = model_path / "transformer" if (model_path / "transformer").exists() else model_path
    model = PixelDiTTransformer2DModel.from_pretrained(str(transformer_path))
    state_dict = model.to_pixeldit_checkpoint(prefix=args.prefix)

    metadata_path = Path(args.metadata_path) if args.metadata_path else model_path / "conversion_metadata.json"
    model_type = None
    if metadata_path.exists():
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        model_type = metadata.get("model_type") or metadata.get("pixeldit_args", {}).get("model_type")
    if model_type is None:
        model_type = _infer_model_type_from_config(model.config)
    if model_type is None:
        raise ValueError(
            "Could not infer PixelDiT model_type from config. "
            "Pass --metadata_path generated by convert_pixeldit_to_diffusers.py."
        )

    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if args.safe_serialization and output_path.suffix == ".safetensors":
        if safe_save_file is None:
            raise ImportError("Install safetensors or use a .bin output path.")
        safe_save_file(state_dict, str(output_path), metadata={"format": "pt", "model_type": model_type})
    else:
        torch.save({"model": state_dict, "model_type": model_type}, str(output_path))

    print(f"Saved PixelDiT checkpoint to: {output_path}")


if __name__ == "__main__":
    main()
